/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    newMap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HelloWorld_newMap
  (JNIEnv *, jclass);

/*
 * Class:     HelloWorld
 * Method:    deleteMap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_deleteMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HelloWorld
 * Method:    mapSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_HelloWorld_mapSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HelloWorld
 * Method:    putIntoMap
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_putIntoMap
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     HelloWorld
 * Method:    getFromMap
 * Signature: (J[BLMapGetter;)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_getFromMap
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     HelloWorld
 * Method:    deleteFromMap
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_deleteFromMap
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
