/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RustMap */

#ifndef _Included_RustMap
#define _Included_RustMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RustMap
 * Method:    newMap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_RustMap_newMap
  (JNIEnv *, jclass);

/*
 * Class:     RustMap
 * Method:    deleteMap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_RustMap_deleteMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     RustMap
 * Method:    mapSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_RustMap_mapSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     RustMap
 * Method:    putIntoMap
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_RustMap_putIntoMap
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     RustMap
 * Method:    getFromMap
 * Signature: (J[BLMapGetter;)V
 */
JNIEXPORT void JNICALL Java_RustMap_getFromMap
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     RustMap
 * Method:    deleteFromMap
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_RustMap_deleteFromMap
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
